[tool.poetry]
name = "shipyard-googlecloud"
version = "0.1.0"
description = "A local client for connecting and working with Google Cloud Service"
authors = ["wrp801 <wespoulsen@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "shipyard_googlecloud"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
google-cloud-storage = "2.7.0"
httplib2 = "0.15.0"
shipyard-templates = "0.5.0a0"
shipyard-utils = "^0.1.4"

[tool.poetry.group.dev.dependencies]
#shipyard-templates = {path = "../../shipyard-templates", develop = true}
pytest = "^7.4.0"
python-dotenv = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
