[tool.poetry]
name = "shipyard-googlecloud"
version = "0.1.0"
description = "A local client for connecting and working with Google Cloud Service"
authors = ["wrp801 <wespoulsen@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "shipyard_googlecloud"}]

[tool.poetry.dependencies]
python = "^3.9"
google-cloud-storage = "2.7.0"
httplib2 = "0.15.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
