[tool.poetry]
name = "shipyard-redshift"
version = "0.2.0"
description = "A local client for connecting and working with Redshift Databases"
authors = ["wrp801 <wespoulsen@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "shipyard_redshift"}]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "1.5.3"
redshift-connector = "2.0.913"
shipyard-templates = "0.8.0a2"
sqlalchemy-redshift = "0.8.14"
shipyard-bp-utils = "1.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
python-dotenv = "^1.0.1"
black = "^24.3.0"

[tool.pytest.ini_options]
testpaths = [
    "tests"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
