[project]
name = "shipyard-asana"
version = "0.1.0"
description = ""
requires-python = ">=3.9"
dependencies = [
    "asana>=3.2.1",
    "shipyard-templates>=0.1.4",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "python-dotenv>=1.0.1",
]
