[tool.poetry]
name = "shipyard-microsoft-teams"
version = "0.1.0"
description = "CLI tool to send messages to Microsoft Teams"
authors = ["JR <johnathan.rodriguez@shipyardapp.com>"]
readme = "README.md"
packages = [{include = "shipyard_microsoft_teams"}]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
