[project]
name = "shipyard-microsoft-teams"
version = "0.2.0a0"
description = "CLI tool to send messages to Microsoft Teams"
requires-python = ">=3.9"
dependencies = [
    "requests>=2.31.0",
    "shipyard-templates>=0.9.0",
    "msal>=1.30.0",
]

[dependency-groups]
dev = [
    "python-dotenv>=1.0.1",
]
