[project]
name = "shipyard-jira"
version = "0.1.3"
description = "A local client for connecting and working with Jira"
requires-python = ">=3.9"
dependencies = [
    "requests>=2.30.0",
    "shipyard-templates>=0.1.2",
]

[dependency-groups]
dev = [
    "python-dotenv>=1.0.1",
    "pytest>=8.2.1",
]
