[tool.poetry]
name = "shipyard-census"
version = "0.2.0"
description = "A local client for connecting and working with Census"
authors = ["JR <johnathan.rodriguez@shipyardapp.com>", "wrp801 <wespoulsen@gmail.com>"]
license = "Apache 2.0"
#readme = "README.md"
packages = [{ include = "shipyard_census" }]

[tool.poetry.dependencies]
python = "^3.9"
requests = "2.31.0"


shipyard-templates = "^0.8.2"
shipyard-bp-utils = "^1.2.1"

[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
