[project]
name = "shipyard-mode"
version = "0.2.1"
description = "A local client for connecting and working with Mode"
requires-python = ">=3.9"
dependencies = [
    "requests>=2.31.0",
    "shipyard-bp-utils>=1.2.1",
    "shipyard-templates>=0.8.2",
]

[dependency-groups]
dev = [
    "python-dotenv>=1.0.1",
]
