[tool.poetry]
name = "shipyard-mode"
version = "0.1.1a0"
description = "A local client for connecting and working with Mode"
authors = ["wrp801 <wespoulsen@gmail.com>"]
license = "Apache 2.0"
#readme = "README.md"
packages = [{ include = "shipyard_mode" }]

[tool.poetry.dependencies]
python = "^3.9"
requests = "2.28.0"
shipyard-utils = "0.1.2"
[tool.poetry.group.dev.dependencies]

shipyard-templates = { path = "../../shipyard-templates" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
