[tool.poetry]
name = "shipyard-microsoft-onedrive"
version = "0.1.0a0"
description = ""
authors = ["wrp801 <wespoulsen@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "2.31"
office365-rest-python-client = "^2.5.10"
pandas = "^2.0"
msal = "^1.28.1"
shipyard-bp-utils = "^1.2.1"
shipyard-templates = "0.9.0a0"


[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.1"
black = "^24.4.2"
pytest = "^8.2.2"
# shipyard-templates = {path = "../../shipyard-templates", develop = true}

[tool.pytest.ini_options]
testpaths = [
    "tests"
]



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

