[project]
name = "shipyard-looker"
version = "0.2.0"
description = "A local client for connecting and looking with Looker"
requires-python = ">=3.9"
dependencies = [
    "looker-sdk==22.20.0",
    "shipyard-templates==0.8.0",
    "shipyard-utils==0.1.4",
    "shipyard-bp-utils>=1.2.0",
]

[dependency-groups]
dev = [
    "python-dotenv>=1.0.1",
    "pytest>=8.1.1",
    "black>=24.3.0",
]
