[tool.poetry]
name = "shipyard-looker"
version = "0.1.1a0"
description = "A local client for connecting and looking with Looker"
authors = ["wrp801 <wespoulsen@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "shipyard_looker"}]

[tool.poetry.dependencies]
python = "^3.9"
looker-sdk = "22.20.0"
shipyard-bp-utils= "0.1.1"
[tool.poetry.group.dev.dependencies]
shipyard-utils="0.1.4"

shipyard-templates = {path = "../../shipyard-templates"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
