[tool.poetry]
name = "shipyard-looker"
version = "0.2.0a0"
description = "A local client for connecting and looking with Looker"
authors = ["wrp801 <wespoulsen@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "shipyard_looker"}]

[tool.poetry.dependencies]
python = "^3.9"
looker-sdk = "22.20.0"
shipyard-templates = "0.8.0"
shipyard-utils="0.1.4"
shipyard-bp-utils = "^1.2.0"

[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.1"
pytest = "^8.1.1"
black = "^24.3.0"

[tool.pytest.ini_options]
testpaths = [
    "tests"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
