[tool.poetry]
name = "postgres-legacy"
version = "0.1.0"
description = ""
authors = ["wrp801 <wespoulsen@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
SQLAlchemy = "1.3.18"
psycopg2-binary = "2.8.5"
pandas = "1.0.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
