[tool.poetry]
name = "shipyard-smartsheets"
version = "0.1.1"
description = ""
authors = ["wrp801 <wespoulsen@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
smartsheet-python-sdk = "^3.0.2"
pandas = "^2.0"
requests = "2.31"
openpyxl = "^3.1.2"
shipyard-templates = "^0.8.2"
shipyard-bp-utils = "^1.2.1"


[tool.poetry.group.dev.dependencies]
black = "^23.10.0"
python-dotenv = "^1.0.0"
pytest = "^8.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
