[project]
name = "shipyard-smartsheets"
version = "0.1.1"
description = ""
requires-python = ">=3.9"
dependencies = [
    "smartsheet-python-sdk>=3.0.2",
    "pandas>=2.0",
    "requests==2.31",
    "openpyxl>=3.1.2",
    "shipyard-templates>=0.8.2",
    "shipyard-bp-utils>=1.2.1",
]

[dependency-groups]
dev = [
    "black>=23.10.0",
    "python-dotenv>=1.0.0",
    "pytest>=8.2.1",
]
