[project]
name = "shipyard-openai-chatgpt"
version = "0.1.1a1"
description = ""
requires-python = ">=3.9"
dependencies = [
    "openai==0.28.1",
    "pandas==1.5.3",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "python-dotenv>=1.0.1",
]
