# General Exit Codes
EXIT_CODE_UNKNOWN_ERROR = 3

# Bad Inputs
EXIT_CODE_INVALID_CREDENTIALS = 200
EXIT_CODE_INVALID_INSTANCE = 201
EXIT_CODE_DBFS_INVALID_SOURCE = 202
EXIT_CODE_INVALID_CLUSTER = 203
EXIT_CODE_BAD_REQUEST = 204

# CLUSTER
EXIT_CODE_CLUSTER_STATUS_TERMINATING = 205
EXIT_CODE_CLUSTER_STATUS_ERRORED = 206
EXIT_CODE_TERMINATION_SUCCESSFULLY_STARTED = 207
EXIT_CODE_CLUSTER_STATUS_RUNNING = 208
EXIT_CODE_CLUSTER_STATUS_RESTARTING = 209

# DBFS EXIT CODES
EXIT_CODE_DBFS_MOVE_ERROR = 210
EXIT_CODE_DBFS_READ_ERROR = 211
EXIT_CODE_DBFS_INVALID_FILEPATH = 212
EXIT_CODE_DBFS = 213
EXIT_CODE_DBFS_INVALID_SOURCE = 214
