[tool.poetry]
name = "shipyard-dropbox"
version = "0.1.1"
description = "A local client to connect and work with Dropox"
authors = ["wrp801 <wespoulsen@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{ include = "shipyard_dropbox" }]

[tool.poetry.dependencies]
python = "^3.9"
shipyard-templates = "^0.7.0"
dropbox = "^11.36.2"
shipyard-bp-utils = "^1.2.0"



[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.1"
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"