[tool.poetry]
name = "shipyard-dbt"
version = "0.2.0"
description = ""
authors = ["wrp801 <wespoulsen@gmail.com>"]
readme = "README.md"
packages = [{include = "shipyard_dbt"}]

[tool.poetry.dependencies]
python = "^3.9"
requests = "2.31.0"
shipyard-templates = "^0.8.2"
shipyard-bp-utils = "^1.2.0"

[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.1"
pytest = "^8.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
