[tool.poetry]
name = "shipyard-shortcut"
version = "0.1.1"
description = "A local client for connecting and working with the shortcut app"
authors = ["JR <johnathan.rodriguez@shipyardapp.com>"]
readme = "README.md"
packages = [{include = "shipyard_shortcut"}]

[tool.poetry.dependencies]
python = "^3.9"
requests = "2.28.0"
shipyard-templates = "^0.1.4"

[tool.poetry.group.dev.dependencies]
shipyard-templates = {path = "../../shipyard-templates", develop = true}
shipyard-bp-utils = {path = "../shipyard-bp-utils", develop = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
