[project]
name = "shipyard-shortcut"
version = "0.1.3"
description = "A local client for connecting and working with the shortcut app"
requires-python = ">=3.9"
dependencies = [
    "requests==2.28.0",
    "shipyard-templates>=0.1.4",
]
