[tool.poetry]
name = "legacy-snowflake"
version = "0.1.0"
description = ""
authors = ["wrp801 <wespoulsen@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
snowflake-connector-python = {version = "*", extras = ["pandas"]}
pandas = "1.3.5"
snowflake-sqlalchemy = "1.4.7"
shipyard-utils = ">=0.1.2"
dask = "2022.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
