[tool.poetry]
name = "shipyard-databricks"
version = "0.1.0"
description = "A local client for connecting and working with Databricks"
authors = ["wrp801 <wespoulsen@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "shipyard_databricks"}]

[tool.poetry.dependencies]
python = "^3.9"
databricks-cli = "^0.17.6"

[tool.poetry.group.dev.dependencies]
shipyard-templates = {path = "../../shipyard-templates"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
