# general error codes
EXIT_CODE_UNKNOWN_ERROR = 3
EXIT_CODE_INVALID_CREDENTIALS = 200
EXIT_CODE_BAD_REQUEST = 201

# run report specific
EXIT_CODE_INVALID_REPORT_ID = 203
EXIT_CODE_INVALID_ACCOUNT = 204

# verify status specific
EXIT_CODE_FINAL_STATUS_SUCCESS = 0
EXIT_CODE_FINAL_STATUS_PENDING = 210
EXIT_CODE_FINAL_STATUS_FAILED = 211
EXIT_CODE_FINAL_STATUS_CANCELLED = 213
EXIT_CODE_FINAL_STATUS_NOT_STARTED = 214
