EXIT_CODE_LOOK_QUERY_ERROR = 203
EXIT_CODE_LOOK_ERROR = 204
EXIT_CODE_LOOK_DASHBOARD_ERROR = 205
EXIT_CODE_SLUG_NOT_FOUND = 206
EXIT_CODE_INVALID_DASHBOARD_ID = 206
EXIT_CODE_INVALID_CREDENTIALS = 207
EXIT_CODE_INVALID_LOOK_ID = 208
EXIT_CODE_INVALID_SLUG = 209