[tool.poetry]
name = "shipyard-trello"
version = "0.1.1"
description = "A local client for connecting a working with Trello."
authors = ["JR <johnathan.rodriguez@shipyardapp.com>"]
readme = "README.md"
packages = [{ include = "shipyard_trello" }]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
shipyard-templates = "0.1.4"

[tool.poetry.group.dev.dependencies]
shipyard-templates = { path = "../../shipyard-templates", develop = true }
shipyard-bp-utils = { path = "../shipyard-bp-utils", develop = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
