[project]
name = "shipyard-trello"
version = "0.1.2a0"
description = "A local client for connecting a working with Trello."
requires-python = ">=3.9"
dependencies = [
    "requests>=2.31.0",
    "shipyard-templates>=0.8.2",
]

[dependency-groups]
dev = [
    "python-dotenv>=1.0.1",
]
