[project]
name = "shipyard-openai-whisper"
version = "0.1.1a0"
description = ""
requires-python = ">=3.9"
dependencies = [
    "openai>=1.6.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "python-dotenv>=1.0.1",
]
