[tool.poetry]
name = "shipyard-bigquery"
version = "0.1.0"
description = "A local client for connecting to and working with Google BigQuery"
authors = ["wrp801 <wespoulsen@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "shipyard_bigquery"}]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "1.5.3"
google-cloud-bigquery = "3.10.0"
db-dtypes = "1.1.1"


[tool.poetry.group.dev.dependencies]
shipyard-templates = {path = "../../shipyard-templates"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
