[tool.poetry]
name = "shipyard-ftp"
version = "0.1.0"
description = "A local client for connecting and working with FTP servers"
authors = ["wrp801 <wespoulsen@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "shipyard_ftp"}]

[tool.poetry.dependencies]
python = "^3.9"
shipyard-templates = "^0.2.0"

[tool.poetry.group.dev.dependencies]
shipyard-bp-utils = {path = "../shipyard-bp-utils"}
shipyard-templates = {path = "../../shipyard-templates"}
pytest = "^7.4.0"
python-dotenv = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
