[tool.poetry]
name = "shipyard-ftp"
version = "0.1.0"
description = "A local client for connecting and working with FTP servers"
authors = ["wrp801 <wespoulsen@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "shipyard_ftp"}]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
shipyard-templates = "0.5.0a0"
shipyard-utils = "0.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
