[tool.poetry]
name = "shipyard-athena"
version = "0.1.0"
description = "A local client for connecting to and working with Amazon Athena"
authors = ["wrp801 <wespoulsen@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "shipyard_athena"}]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "1.14.32"
shipyard-templates = "^0.1.0"

[tool.poetry.group.dev.dependencies]
shipyard-templates = {path = "../../shipyard-templates"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
