[project]
name = "shipyard-salesforce"
version = "0.1.1"
description = ""
requires-python = ">=3.9"
dependencies = [
    "shipyard-templates==0.3.1",
    "requests>=2.31.0",
    "pandas>=2.1.0",
    "shipyard-bp-utils==0.1.1",
]

[dependency-groups]
test = [
    "pytest>=7.4.0",
    "python-dotenv>=1.0.0",
    "pytest-dotenv>=0.5.2",
    "requests-mock>=1.11.0",
]
