[project]
name = "shipyard-portable"
version = "0.1.0"
description = ""
requires-python = ">=3.9"
dependencies = [
    "requests>=2.31.0",
    "shipyard-templates>=0.8.1",
    "shipyard-bp-utils>=1.2.0",
]

[dependency-groups]
dev = [
    "pytest>=8.1.1",
    "python-dotenv>=1.0.1",
]
