[project]
name = "shipyard-microsoft-sharepoint"
version = "0.1.0"
description = "A local client for working with Microsoft SharePoint"
requires-python = ">=3.9"
dependencies = [
    "shipyard-templates>=0.9.0",
    "requests==2.31",
    "msal>=1.30.0",
    "shipyard-bp-utils>=1.2.1",
]

[dependency-groups]
dev = [
    "python-dotenv>=1.0.1",
    "black>=24.4.2",
    "pytest>=8.3.1",
]
