EXIT_CODE_FINAL_STATUS_SUCCESS = 0
EXIT_CODE_UNKNOWN_ERROR = 3

EXIT_CODE_INVALID_CREDENTIALS = 200
EXIT_CODE_INVALID_ACCOUNT = 201
EXIT_CODE_BAD_REQUEST = 202
EXIT_CODE_DATASET_NOT_FOUND = 203
EXIT_CODE_EXECUTION_ID_NOT_FOUND = 204
EXIT_CODE_INCORRECT_CARD_TYPE = 205
EXIT_CODE_REFRESH_ERROR = 206
EXIT_CODE_USERNAME_PASSWORD_NOT_ACCEPTED = 207

EXIT_CODE_FINAL_STATUS_INVALID = 210
EXIT_CODE_FINAL_STATUS_CANCELLED = 211
EXIT_CODE_STATUS_INCOMPLETE = 212
EXIT_CODE_UNKNOWN_STATUS = 213

EXIT_CODE_FILE_NOT_FOUND = 214
EXIT_CODE_DATASET_NOT_FOUND = 215

EXIT_CODE_DUPLICATE_DATASET = 216
EXIT_CODE_NON_API_DATASET = 217

EXIT_CODE_INVALID_DATA_TYPE = 218
EXIT_CODE_COLUMN_MISMATCH = 219
