name: Vendor Package Tests

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: changed
        continue-on-error: true
        name: Get changed files
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})    
          echo "All changed files:"
          
          for file in $changed_files; do
            echo "$file"
          done
          
          changed_files=$(echo "$changed_files" | grep shipyard_blueprints)
          
          echo "Filtered changed files:"
          
          for file in $changed_files; do
            echo "$file"
          done
          
          echo "CHANGED_FILES<<$changed_files" >> $GITHUB_ENV

      - name: No changes
        if: ${{ !env.CHANGED_FILES }}
        run: |
          echo "No file changes detected."
          exit 0

      - name: Install dependencies
        if: env.CHANGED_FILES
        run: |
          for file in ${{ env.CHANGED_FILES }}; do
            cd ./shipyard_blueprints/$file
            poetry install
          done

      - name: Run tests
        if: env.CHANGED_FILES
        run: |
          for file in ${{ env.CHANGED_FILES }}; do
            cd ./shipyard_blueprints/$file
            poetry run pytest
          done