name: PyTests

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Get changed files
        id: set-matrix
        run: |
          changed_vendors=$(python3 .github/workflows/scripts/trigger_pytests_on_vendor_changes.py ${{ github.event.before }} ${{ github.event.after }})
          # Convert newline-separated values to comma-separated
          matrix_values=$(echo "$changed_vendors" | tr '\n' ',' | sed 's/,$//')
          echo "MATRIX_VALUES=[$matrix_values]" >> $GITHUB_ENV
          echo "::set-output name=matrix::[$matrix_values]"