name: PyTests

on: [ push ]

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - id: set-matrix
        name: Get changed files and set matrix
        run: |
          changed_vendors=$(python3 .github/workflows/scripts/get_modified_blueprints.py ${{ github.event.before }} ${{ github.event.after }} | tr '\n' ',' | sed 's/,$//')
          echo "Changed vendors: $changed_vendors"
          if [[ -z "$changed_vendors" ]]; then
            echo "No vendor package changes detected."
            echo "::set-output name=matrix::[]"
          else
            echo "::set-output name=matrix::[\"${changed_vendors//,/\",\"}\"]"
          fi

  no_changes_message:
    needs: detect_changes
    runs-on: ubuntu-latest
    if: needs.detect_changes.outputs.matrix == '[]'
    steps:
      - name: Print no changes message
        run: echo "No vendor changes detected, skipping tests."

  test:
    name: Run tests
    needs: detect_changes
    runs-on: ubuntu-latest
    if: needs.detect_changes.outputs.matrix != '[]'
    strategy:
      matrix:
        vendor: ${{fromJson(needs.detect_changes.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Run tests
        run: |
          cd shipyard_blueprints/${{ matrix.vendor }}
          poetry add pytest
          poetry install
          poetry run pytest
