name: PyTests

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: changed
        continue-on-error: true
        name: Get changed files
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})    
          echo "All changed files:"
          
          for file in $changed_files; do
            echo "$file"
          done
          
          changed_dirs=$(echo "$changed_files" | grep "^shipyard_blueprints" | awk -F/ 'NF>2{OFS="/"; $NF=""; print $0}' | sed 's/\/$//')
          # Remove duplicates
          changed_dirs=$(echo "$changed_dirs" | sort | uniq)
          
          echo "Filtered changed directories:"
          
          for dir in $changed_dirs; do
            echo "$dir"
          done
          
          echo "CHANGED_DIRS<<$changed_dirs" >> $GITHUB_ENV

      - name: No changes
        if: ${{ !env.CHANGED_DIRS }}
        run: |
          echo "No directory changes detected."
          exit 0

      - name: Install dependencies
        if: env.CHANGED_DIRS
        run: |
          for dir in ${{ env.CHANGED_DIRS }}; do
            cd ./$dir
            poetry install
          done

      - name: Run tests
        if: env.CHANGED_DIRS
        run: |
          for dir in ${{ env.CHANGED_DIRS }}; do
            cd ./$dir
            poetry run pytest
          done
