name: Python Tests

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed files
      run: |  
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep shipyard_blueprints || echo "")
        if [ -z "$changed_files" ]; then
          echo "No changed files found."
          echo "::set-output name=skip::true"
        else
          echo "::set-output name=changed_files::$changed_files"
          echo "::set-output name=skip::false"
        fi
      id: changed

    - name: Install dependencies
      if: steps.changed.outputs.changed_files != ''
      working-directory: ./shipyard_blueprints/${{ steps.changed.outputs.changed_files[0] }}
      run: |
        poetry install

    - name: Run tests
      if: steps.changed.outputs.changed_files != ''
      working-directory: ./shipyard_blueprints/${{ steps.changed.outputs.changed_files[0] }}
      run: |
        poetry run pytest