name: PyTests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - id: changed
        continue-on-error: true
        name: Get changed files
        run: |
          changed_vendors=$(python3 .github/workflows/scripts/get_modified_blueprints.py ${{ github.event.before }} ${{ github.event.after }})
          echo "Changed vendors:"
          echo $changed_vendors
          vendors = $changed_vendors
          
          echo "CHANGED_VENDORS=${vendors[*]}" >> $GITHUB_ENV

      - name: No changes
        if: ${{ !env.CHANGED_VENDORS }}
        run: |
          echo "No vendor package changes detected."
          exit 0

      - name: Install Poetry
        if: env.CHANGED_VENDORS
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Run tests
        if: env.CHANGED_VENDORS
        run: |
          for vendor in ${{ env.CHANGED_VENDORS }}; do
            cd shipyard_blueprints/$vendor
            poetry install
            poetry run pytest
          done
