name: PyTests

on: [ push ]

jobs:
  find-vendors:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Get changed files
        id: set-matrix
        run: |
          changed_vendors=$(python3 .github/workflows/scripts/get_modified_blueprints.py ${{ github.event.before }} ${{ github.event.after }})
          # Convert newline-separated values to comma-separated
          matrix_values=$(echo "$changed_vendors" | tr '\n' ',' | sed 's/,$//')
          echo "::set-output name=matrix::[$matrix_values]"

  test:
    needs: find-vendors
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vendor: ${{fromJson(needs.find-vendors.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Run tests for ${{ matrix.vendor }}
        run: |
          cd shipyard_blueprints/${{ matrix.vendor }}
          poetry install
          poetry run pytest
