name: Python Tests

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

- name: Get changed files
  run: |  
    changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep shipyard_blueprints)
    echo "::set-output name=changed_files::$changed_files"
  id: changed

    - name: Install dependencies
      if: steps.changed.outputs.changed_files != ''
      working-directory: ./shipyard_blueprints/${{ steps.changed.outputs.changed_files[0] }}
      run: |
        poetry install

    - name: Run tests
      if: steps.changed.outputs.changed_files != ''
      working-directory: ./shipyard_blueprints/${{ steps.changed.outputs.changed_files[0] }}
      run: |
        poetry run pytest