[project]
name = "shipyard-rudderstack"
version = "0.0.1"
authors = [
  {name="Shipyard Team", email="tech@shipyardapp.com" },
]
description = "Simplified data pipeline blueprints for working with Rudderstack."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/shipyardapp/shipyard-blueprints"
"Bug Tracker" = "https://github.com/shipyardapp/shipyard-blueprints/issues"