[tool.poetry]
name = "shipyard-rudderstack"
version = "0.1.0"
description = "A local client for connecting and working with Rudderstack"
authors = ["JR <johnathan.rodriguez@shipy>", "wrp801 <wespoulsen@gmail.com>"]
readme = "README.md"
packages = [{ include = "shipyard_rudderstack" }]

[tool.poetry.dependencies]
python = "^3.9"
requests = "2.31.0"
shipyard-templates = "0.1.7"
shipyard-utils = "0.1.4"

[tool.poetry.group.dev.dependencies]
shipyard-templates = { path = "../../shipyard-templates" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


