[project]
name = "shipyard-rudderstack"
version = "0.1.1"
description = "A local client for connecting and working with Rudderstack"
requires-python = ">=3.9"
dependencies = [
    "requests==2.31.0",
    "shipyard-templates==0.1.7",
    "shipyard-utils==0.1.4",
]

[dependency-groups]
dev = [
    "pytest>=8.2.1",
    "python-dotenv>=1.0.1",
]
